plugin:
    name: 'nielsvandendries.twitchembed::lang.plugin.name'
    description: 'nielsvandendries.twitchembed::lang.plugin.description'
    author: 'Niels van den Dries'
    icon: oc-icon-video-camera
    homepage: 'https://nvandendries.nl'
permissions:
    channels:
        tab: 'nielsvandendries.twitchembed::lang.plugin.name'
        label: Channels
    vod:
        tab: 'nielsvandendries.twitchembed::lang.plugin.name'
        label: VOD
navigation:
    main-menu-item:
        label: 'nielsvandendries.twitchembed::lang.plugin.name'
        url: /
        icon: icon-twitch
        permissions:
            - channels
        sideMenu:
            side-menu-item:
                label: Channels
                url: nielsvandendries/twitchembed/channels
                icon: icon-video-camera
                permissions:
                    - channels
            side-menu-item2:
                label: VOD
                url: nielsvandendries/twitchembed/vod
                icon: icon-play-circle
                permissions:
                    - vod
